services:
  - type: web
    name: alshalal-bms-api
    env: node
    buildCommand: npm install
    startCommand: npm run server
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
